services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seo_backend
    ports:
      - "8003:8003"
    env_file:
      - ./backend/.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    volumes:
      - ./backend:/app
      - ./backend/reports:/app/reports
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seo_frontend
    ports:
      - "3003:3003"
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
